### ISSUE TITLE
Can we use this in Drupal 7?

### ISSUE THREAD

**Issue by tarunhere** [spatie/drupal-ray#2]
Hi, 
I need to debug old Drupal 7 application and I am new with drupal as well. Can you guide me with steps if this could be used in that.
Thanks in advance. 
Looking forward for hearing from you. Any pointers wil help.

**Comment by tarunhere** [comment]
There is no code in it. How can we use it in Drupal?

**Comment by freekmurze** [comment]
We haven't come around creating this package yet, so we currently can't help you here. Try the framework agnostic integration. Docs at https://spatie.be/docs/ray
